### ISSUE TITLE
Test for timer range

### ISSUE THREAD

**Issue by ivan-pi** [Timendus/chip8-test-suite#13]
First of all, thank you very much for these incredible tests!

I ran into the following issue with my CHIP-8 implementation. The timers were accidentally signed integers, meaning their range was from -128 to 127.

```c
int8_t delay_timer;
    
    // DFX15:
    delay_timer = V[x]:
    pc += 2;
```

Since the timers were only decremented when `delay_timer > 0`, my interpreter would freeze any time `V[x]` contained a value larger than 127. (This happened for instance with the the `5-quirks.ch8` test.)

I'm not sure what would be the right way to catch this?

**Comment by ivan-pi** [comment]
I guess the signed int could also work (assuming wraparound behaviour), as long as the comparison is been performed correctly:

```cpp
if ((uint8_t) delay_timer > 0U) 
    delay_timer--;
```

I suppose the timer could be represented with anything really, but it needs to be able to perform up to 2^8 = 256 ticks before it stops changing.

**Comment by Timendus** [comment]
Yes, interesting issue. And you're welcome! 😄

I'm not sure if this is a class of problem that many people struggle with. I haven't seen it happen often. I'm also not entirely sure how we would test this in a friendly way.

Do you have any suggestions?
