### ISSUE TITLE
Is check at 2EC correct?

### ISSUE THREAD

**Issue by sepkov** [Timendus/chip8-test-suite#26]
Here is the code that does the check: 660B 672A8761 472B -> Location 2EC at memory. 
As far as I understand the program assigns V6 -> 0B and V7 -> 2A and OR's them. The result should be stored in V7 as 0x1. However 472B check the V7 for value 0x2B.
 
According to this reference :http://devernay.free.fr/hacks/chip8/C8TECH10.HTM#8xy1

I believe check should be 4701. Check V7 for value 0x1.

Am I wrong or Technical Reference wrong?

**Comment by sepkov** [comment]
Okay nvm I was looking at wrong thing. Thanks for this ROM :)

**Comment by gulrak** [comment]
> According to this reference :http://devernay.free.fr/hacks/chip8/C8TECH10.HTM#8xy1
> [...]
> Am I wrong or Technical Reference wrong?

Just to be sure and for completeness, _that_ "technical reference" _is_ outdated and wrong in various places. Better use something like this: https://github.com/mattmikolay/chip-8/wiki/Mastering-CHIP%E2%80%908 and the pages there.
