### ISSUE TITLE
Flags tests- possible bug/enhancement for 8XY4, 8XY5 and 8XY7 opcodes

### ISSUE THREAD

**Issue by jon-axon** [Timendus/chip8-test-suite#7]
First of all, many thanks for the excellent test suite!  I'm currently developing my first CHIP-8/SCHIP interpreter using a TDD approach and have a large bank of unit tests defined, yet despite this your test suite picked-up a number of subtle problems caused by me misinterpreting nuances of certain instructions (and therefore defining my unit tests wrong as well as my interpreter code), so it's been an invaluable resource.

I'm creating a ticket here to report a potential bug I've spotted while ironing out the last few issues with my interpreter by running as many ROMs as I can get my hands on.  Specifically, I've discovered it's currently possible for an interpreter to pass your **Flags** test with 3 checkmarks for each instruction, despite having an incorrect implementation for opcodes `8XY4`, `8XY5` and `8XY7`.  The issue relates to the behaviour when VF is specified as the VX argument.  As confirmed by [Laurence Scotford](https://laurencescotford.com/chip-8-on-the-cosmac-vip-arithmetic-and-logic-instructions/), the entire family of `8XYN` instructions overwrite variable VF, and so in this particular scenario will overwrite the result with the flag status.  Your **Flags** test correctly checks for this for `8XY6` and `8XYE` when granting the third checkmark, however it does NOT carry out this specific check for `8XY4`, `8XY5` and `8XY7`; your tests never use VF as the VX argument for these opcodes.

I am aware of at least one game where this nuance is important: [Knight](https://johnearnest.github.io/chip8Archive/play.html?p=knight).  My interpreter was hanging on the initial instructions/control screen of this game, and only by stepping through the game code line-by-line was I able to determine the infinite loop was caused by me having set the VF flag status incorrectly as per the above, despite all your **Flags** tests passing.  Incidentally your own Silicon8 interpreter runs Knight correctly, so you are clearly aware of the intended behaviour of these instructions yourself, it's just that the test suite doesn't check for this correctness fully at present other than for `8XY6` and `8XYE`.

I've had a very quick look at your test suite code for these tests to understand what you are currently doing here for the third checkmark for `8XY4`, `8XY5` and `8XY7`.  I think by passing VF as the VY argument you are trying to trap a situation where an implementation is setting the VF flag before actually calculating the final result , which would give incorrect results.  This is also a legitimate test, so I guess there's no easy way to accommodate my "bug", with the options being:

* Replacing your test with mine (which would only be valid if it is a more likely implementation error to occur)
* Introducing a fourth checkmark, which would be ideal, but obviously require a bigger change and a real estate problem :smile:

Anyway, please let me know if you want any more information, and thanks again for an excellent test suite!

**Comment by jon-axon** [comment]
I've actually forked the repo taken a look at what could be done for this, and have been able to include my additional suggested VF check through a slight rearrangement to the **Flags** UI, by abbreviating "CARRY" to "CRY" (which as well as being a suitable abbreviation for "carry" also amused me as a contrast to the "HAPPY" heading above ... although maybe that's just my strange sense of humour!).  This makes space for a 4th checkmark for `8XY4`, `8XY5`, `8XY7`.  The 3rd checkmark in each case works exactly as it does in your current v3 release.  Here is what the revised UI looks like.

This first screenshot shows the test running on the previous build of my interpreter, which contained the bug for opcode `8XY4` , but for which your current tests don't indicate a problem.  As you can see, the new 4th checkmark does now pick up this issue:

![Not works](https://user-images.githubusercontent.com/103050728/224029694-3e00aba4-ca73-4471-ac79-1a39f6bee381.PNG)

Here is the test after I fixed my interpreter:

![Works](https://user-images.githubusercontent.com/103050728/224029961-8008f896-0a9b-4724-80a1-cb172d3c4705.PNG)

What do you think?  The screen layout is not as pleasing/clean as it used to be, but I couldn't see a better way to easily accommodate the extra check.  If you like this then I can raise a PR later on to merge the changes back into your repo, but I'm not offended at all if you don't want to implement this or would rather do it your own way :smile:

**Comment by jon-axon** [comment]
I've now taken a different approach with the revised UI; please see #8 for details.

**Comment by Timendus** [comment]
Thanks for the work you've done on this issue so far! I like the way your second PR looks much more than the first one 😉
